apiVersion: apps/v1
kind: Deployment
metadata:
  name: Workflow
  labels:
    app: Workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Workflow
  template:
    metadata:
      labels:
        app: Workflow
    spec:
      containers:
        - name: Workflow
          image: username/Workflow:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5