apiVersion: apps/v1
kind: Deployment
metadata:
  name: Preprocess
  labels:
    app: Preprocess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Preprocess
  template:
    metadata:
      labels:
        app: Preprocess
    spec:
      containers:
        - name: Preprocess
          image: username/Preprocess:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5